curl 'https://localhost:8001/'
curl 'https://localhost:8001/path?lang=en'
curl 'https://localhost:8001/fragment?section=main'
curl 'https://localhost:8001/safe/redirect?url=fragment%3Fsection%3Dmain'
curl 'https://localhost:8001/safe/fragment?section=main'
